### ISSUE TITLE
QudtQuantityKind SerumOrPlasmaLevel

### ISSUE THREAD

**Issue by GertjanBisschop** [eu-parc/indicator-vocabulary#9]
```
- id: https://w3id.org/peh/IN-b8155ea753
  unique_name: amount per volume of af in blood
  name: amount per volume of af in blood
  label: amount per volume of af in blood
  indicator_type: exposuremarker
  varname: af
  property: amount per volume
  quantity_kind: SerumOrPlasmaLevel
  matrix: blood
  relevant_observable_entity_types:
  - person
  - sample
  biochementity_links:
  - biochementity_linktype: exact_match
    biochementity: Alkaline Phosphatases
```
This entity has a quantiy_kind that is not part of the enumeration as defined in the current peh linkml schema. Possible values are:
```
QudtQuantityKind:
    permissible_values:
      AmountOfSubstanceConcentration:
        meaning: qudtqk:AmountOfSubstanceConcentration
      AmountOfSubstancePerMass:
        meaning: qudtqk:AmountOfSubstancePerMass
      Count:
        meaning: qudtqk:Count
      Dimensionless:
        meaning: qudtqk:Dimensionless
      DimensionlessRatio:
        meaning: qudtqk:DimensionlessRatio
      Time:
        meaning: qudtqk:Time
      Frequency:
        meaning: qudtqk:Frequency
      Length:
        meaning: qudtqk:Length
      Mass:
        meaning: qudtqk:Mass
      MassPerArea:
        meaning: qudtqk:MassPerArea
      MassConcentration:
        meaning: qudtqk:MassConcentration
      MassRatio:
        meaning: qudtqk:MassRatio
      MolarMass:
        meaning: qudtqk:MolarMass
      MolarRatio:
        meaning: qudtqk:MolarRatio
      NumberDensity:
        meaning: qudtqk:NumberDensity
      Volume:
        meaning: qudtqk:Volume
    include:
    - reachable_from:
        source_ontology: qudtqk
        source_nodes:
          - qudtqk:QuantityKind
        include_self: false
        relationship_types:
          - rdfs:subClassOf
```
